(ns lytek.draconic.chron.merit)

(def nameField "meritNameText")
(def descritpion "meritDescriptionText")
(def rank1 "meritRankCheck1")
(def rank2 "meritRankCheck2")
(def rank3 "meritRankCheck3")
(def rank4 "meritRankCheck4")
(def rank5 "meritRankCheck5")
(def andTog "meritAndToggle")
(def orTog "meritOrToggle")
(def prereq "meritPrereqText")
(def tag1 "meritTagText1")
(def tag2 "meritTagText2")
(def tag3 "meritTagText3")
(def tag4 "meritTagText4")
(def tag5 "meritTagText5")

(def fields [nameField descritpion rank1 rank2 rank3 rank4 rank5 andTog orTog prereq tag1 tag2 tag3 tag4 tag5])